# ==================== Take Note - config ====================
# Defaults are commented out.

# APPEND_NOTES is a multi key object that can take names for any
# path as a key of sorts
# eg:
# [APPEND_NOTES]
# myfile = "./appendthisfile.md"
# daily = "./dailynote.md
#
# ==================== ~ ====================

# Set this path
# Absolute paths for global settings, '~/notes/' is okay.
# Relative paths are preferred for local settings
# SAVE_PATH_NOTES = "./"

# Files to append to
# No defaults
# [APPEND_NOTES]
# myfile = "./appendthisfile.md"
