# ==================== Take Note - config ====================
# Defaults are commented out.

# APPEND_NOTES is a multi key object that can take names for any
# path as a key of sorts
# eg:
# [APPEND_NOTES]
# myfile = "./appendthisfile.md"
# daily = "./dailynote.md
#
# ==================== ~ ====================

# Set this path
# Absolute paths for global settings, '~/notes/' is okay.
# Relative paths are preferred for local settings
# SAVE_PATH_NOTES = "./"

# Verbosity
# 0 is only error messages
# 3 is all messages
# VERBOSITY_LEVEL = 1

# Files to append to
# No defaults
# [APPEND_NOTES]
# myfile = "./appendthisfile.md"
# A format for a file to be appended to
# daily = "DATE:YYMM"

# Templating
# [TEMPLATES]
# title.new = "DATE:YYMM_HHmmss"
# title.newwtitle = "new - TITLE"
# Stored in template folder
# new_note = "new-note-.md"
# daily = "daily-appeneder.md"
# daily_new = "daily-new.md"
