# ==================== Take Note - config ====================
# Defaults are commented out, uncomment and edit, they are defined in the code.
#
# ==================== ~ ====================

## Overide for editor environment variable
# EDITOR=vi

## File Extension
# EXTENSION="md"

## Set this path
## Absolute paths for global settings, '~/notes/' is okay.
## Relative paths are preferred for local settings
# SAVE_PATH_NOTES = "./"

## Templates directory path, relative to .tn folder or absolute for anywhere else.
# TEMPLATES_DIR = "./templates"

## Verbosity
## -1 Mute
## 0 Info
## 3 Debug
# VERBOSITY_LEVEL = 1

[APPEND]
## Appending Notes
## Append to any notes declared in the config file.
## An toml object that uses key as a shortcut for a path of a note to append to.
## No defaults, only examples
# myfile = "./appendthisfile.md"

[FORMAT]
## Formatting
## Follows the same syntax as templating.
## Only [date, title] are exposed.
## Title has two formatting options, if a file has no title the short one is generated.
## If note has a title, then you can define how to format the title.
# [FORMAT.FILENAME]
# short = "{{ date.format('%y%m_%d%H%M') }}"
# long = "{{ date.format('%y%m_%d%H%M') }} - {{ title }}"

[TEMPLATES]
## Templating
## Formatting objects [clipboard, date, title, note]
#
## Stored in template folder
## No defaults, only examples
# new_note = "new-note.md"
# daily_new = "daily-new.md"
# link = "link-note.md"
