# ==================== Take Note - config ====================
# Defaults are commented out.

# APPEND_NOTES is a multi key object that can take names for any
# path as a key of sorts
# eg:
# [APPEND_NOTES]
# myfile = "./appendthisfile.md"
# daily = "./dailynote.md
#
# ==================== ~ ====================

# Overide for editor environment variable
# EDITOR=vi

# Set this path
# Absolute paths for global settings, '~/notes/' is okay.
# Relative paths are preferred for local settings
# SAVE_PATH_NOTES = "./"

# Templates directory path, relative to .tn folder or absolute for anywhere else.
# TEMPLATES_DIR = "./templates"

# [FORMAT]
# Title has two formatting options, if a file has no title the short one is generated.
# If note has a title, then you can define how to format the title.
# title={short = "{{ date.format('%y%m_%d%H%M') }}", long = "{{ date.format('%y%m_%d%H%M') }} - {{ title }}"}

# Verbosity
# 0 is only error messages
# 3 is all messages
# VERBOSITY_LEVEL = 1

# Files to append to
# No defaults
# [APPEND_NOTES]
# myfile = "./appendthisfile.md"
# A format for a file to be appended to
# daily = "DATE:YYMM"

# Templating
# [TEMPLATES]
# title.new = "DATE:YYMM_HHmmss"
# title.newwtitle = "new - TITLE"
# Stored in template folder
# new_note = "new-note-.md"
# daily = "daily-appeneder.md"
# daily_new = "daily-new.md"
