repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-ast
      - id: check-docstring-first
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, main]

  # Black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  # Ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.100
    hooks:
      - id: ruff
