[tool.poetry]
name = "takenote"
version = "1.0.0"
description = "Note taking terminal app, for integration with obsidian."
authors = ["proximalf <proximalfuture@gmail.com>"]
license = "MIT"
readme = "readme.md"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [
    { include = "takenote" }
]

[tool.semantic_release]
version_variable = "pyproject.toml:version"
changelog_file = "changelog.md"
branch = "main"
upload_to_pypi = false
upload_to_release = false
#build_command = "pip install poetry && poetry build"


[tool.poetry.scripts]
tn = "takenote:cli"

[tool.poetry.urls]
repository = "https://github.com/proximalf/ubiquitous-octo-disco"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
dynaconf = "^3.1.11"
jinja2 = "^3.1.2"

[tool.poetry.group.dev.dependencies]
python-semantic-release = "^7.32.2"
mypy = "^0.990"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
# A: flake8-annotations
# C: flake8-comprehensions
# D: pydocstyle
# E: pycodestyle
# F: pyflakes
# N: pep8-naming
# T: flake8-print
select = ["A", "C", "D", "E", "F", "N", "T"]
ignore = [
    # Docstyle and codestyle
    "A002",
    "A003",
    "D100",
    "D202",
    "D203",
    "D205",
    "D212",
    "D400",
    "D409",
    "D411",
    "D415",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.mypy]
files = "takenote"
mypy_path = "takenote"
ignore_missing_imports = true
