[project]
name = "take-note"
keywords = ["notes", "terminal", "python"]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
]
author = "proximalf"
author_email = "proximalfuture@gmail.com"
description = "Note taking terminal app, for integration with obsidian."
requires-python = ">=3.9"

[project.urls]
repository = "https://github.com/proximalf/ubiquitous-octo-disco"

[build-system]
requires = ["setuptools ~= 58.0", "cython ~= 0.29.0"]

[tool.ruff]
line-length = 120
select = ["E", "F"]
ignore = [

    ]
per-file-ignores = [
    "__init__.py:F401",
    "path/to/file.py:F401"
]
