[tool.poetry]
name = "takenote"
version = "0.0.1"
description = "Note taking terminal app, for integration with obsidian."
authors = ["proximalf <proximalfuture@gmail.com>"]
license = "MIT"
readme = "readme.md"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
]
packages = [
    { include = "takenote" }
]

[tool.poetry.urls]
repository = "https://github.com/proximalf/ubiquitous-octo-disco"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
line-length = 120
#select = ["E", "F"]
ignore = [

    ]
per-file-ignores = [
    "__init__.py:F401",
    #"path/to/file.py:F401"
]
